### ISSUE TITLE
nice !

### ISSUE THREAD

**Issue by FGRibreau** [mpneuried/ex-redis-sessions#2]
Nice lib @mpneuried! It will be shared in RedisWeekly ( http://redisweekly.com ) tomorrow!

**Comment by mpneuried** [comment]
**Oh, thanks!**

But just a note: The lib is currently in development. I'm just done with the main methods.
And because this is my first elixir module there is some code optimization pending ;-)

But i'm planning to finish it at least early next week in a first version.
